[package]
name = "t2meili"
description = "convert torrent metadata to json lines"
repository = "https://github.com/xfnw/t2meili/"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
lava_torrent = "0.11.1"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
